default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username:
  password:

development:
  <<: *default
  database: im_dev

test:
  <<: *default
  database: im_test

production:
  <<: *default
  database: im_prod
  username:
  password:
